DELETE http://localhost:3000/api/members/1
Content-Type: application/json

###
GET http://localhost:3000/api/members/
Accept: application/json

###
PUT http://localhost:3000/api/members/1
Content-Type: application/json

  {
    "id": 1,
    "name": "Alex",
    "team": "engineering",
    "position": "backendDeveloper",
    "emailAddress": "alex@google.com",
    "phoneNumber": "010-xxxx-xxxx",
    "admissionDate": "2018/12/10",
    "birthday": "1994/11/08",
    "profileImage": "profile1.png"
  }
###
